#
# Archivo: Makefile
#
# Nombres:
#	Alejandra Cordero / Carnet: 12-10645
#	Pablo Maldonado   / Carnet: 12-10561
#
# Ultima modificacion: 09/05/2015
#
#

Main:
	gcc mainP.c -o friendfindP
	gcc map.c -o map

clean:
	rm friendfindP
