#
# Archivo: Makefile
#
# Nombres:
#	Alejandra Cordero / Carnet: 12-10645
#	Pablo Maldonado   / Carnet: 12-10561
#
# Ultima modificacion: 18/04/2015
#
#

all:
	gcc -o preguntas *.c
clean:
	rm preguntas
