#
# Archivo: Makefile
#
# Nombres:
#	Alejandra Cordero / Carnet: 12-10645
#	Pablo Maldonado   / Carnet: 12-10561
#
# Ultima modificacion: 07/06/2015
#
#

Main:
	gcc -Wall -g main.c lib_cuentos.c -o MiCuento

MiCuento.o: main.c lib_cuentos.h
	gcc -c main.c

clean:
	rm MiCuento
